[package]
name = "syslog-simulator"
version = "0.1.0"
edition = "2025"

[dependencies]
clap = { version = "4.3", features = ["derive"] }
tokio = { version = "1.29", features = ["full"] }
chrono = "0.4"
rand = "0.8"
native-tls = "0.2"
tokio-native-tls = "0.3"
